-- =====================================================================
-- VR Store Website & Billing Studio — Complete Supabase Setup Schema
-- =====================================================================
-- Run this in: https://supabase.com/dashboard/project/mjdftntxhshgxfxtinyl/sql
-- =====================================================================

-- Drop legacy table if present
DROP TABLE IF EXISTS public.admin_users CASCADE;

-- 1. STOREFRONT PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
    id          BIGINT PRIMARY KEY,
    name        TEXT NOT NULL,
    brand       TEXT,
    capacity    TEXT,
    type        TEXT,
    price       NUMERIC DEFAULT 0,
    description TEXT,
    featured    BOOLEAN DEFAULT FALSE,
    image       TEXT,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 2. SERVICE BOOKINGS TABLE
CREATE TABLE IF NOT EXISTS public.bookings (
    id             TEXT PRIMARY KEY DEFAULT ('BK-' || floor(random()*9000+1000)::TEXT),
    name           TEXT NOT NULL,
    phone          TEXT NOT NULL,
    email          TEXT,
    service_type   TEXT,
    ac_type        TEXT,
    preferred_date TEXT,
    address        TEXT,
    status         TEXT DEFAULT 'Pending',
    notes          TEXT,
    created_at     TIMESTAMPTZ DEFAULT NOW()
);

-- 3. CONTACT MESSAGES TABLE
CREATE TABLE IF NOT EXISTS public.messages (
    id         TEXT PRIMARY KEY DEFAULT ('MSG-' || floor(random()*90000+10000)::TEXT),
    name       TEXT NOT NULL,
    phone      TEXT NOT NULL,
    email      TEXT,
    message    TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ADMIN USERS TABLE
CREATE TABLE IF NOT EXISTS public.admin (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL DEFAULT 'Administrator',
    email         TEXT UNIQUE NOT NULL,
    username      TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role          TEXT DEFAULT 'superadmin',
    created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- 5. SETTINGS / CONFIG TABLE (AMC Pricing, etc.)
CREATE TABLE IF NOT EXISTS public.settings (
    key        TEXT PRIMARY KEY,
    value      JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. INVOICE GENERATOR CUSTOMERS TABLE
CREATE TABLE IF NOT EXISTS public.customers (
    id              TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    address         TEXT,
    mobile          TEXT,
    gstin           TEXT,
    ship_name       TEXT,
    ship_address    TEXT,
    ship_mobile     TEXT,
    ship_ref        TEXT,
    place_of_supply TEXT,
    notes           TEXT,
    created         TIMESTAMPTZ DEFAULT NOW(),
    updated         TIMESTAMPTZ DEFAULT NOW()
);

-- 7. INVOICE GENERATOR DOCUMENTS / BILLS TABLE
CREATE TABLE IF NOT EXISTS public.documents (
    id            TEXT PRIMARY KEY,
    doc_type      TEXT NOT NULL,
    doc_no        TEXT NOT NULL,
    doc_date      TEXT,
    customer_id   TEXT,
    customer_name TEXT,
    taxable       NUMERIC DEFAULT 0,
    tax           NUMERIC DEFAULT 0,
    other_charges NUMERIC DEFAULT 0,
    total         NUMERIC DEFAULT 0,
    advance       NUMERIC DEFAULT 0,
    balance       NUMERIC DEFAULT 0,
    json_data     JSONB NOT NULL,
    created       TIMESTAMPTZ DEFAULT NOW()
);

-- 8. INVENTORY STOCK CATALOG TABLE
CREATE TABLE IF NOT EXISTS public.stock (
    id       TEXT PRIMARY KEY,
    model    TEXT NOT NULL,
    hsn      TEXT,
    ton      TEXT,
    type     TEXT,
    mrp      NUMERIC DEFAULT 0,
    rate     NUMERIC DEFAULT 0,
    cost     NUMERIC DEFAULT 0,
    gst      NUMERIC DEFAULT 0,
    qty      NUMERIC DEFAULT 0,
    reorder  NUMERIC DEFAULT 0,
    location TEXT,
    updated  TIMESTAMPTZ DEFAULT NOW()
);

-- 9. INVENTORY STOCK MOVEMENTS TABLE
CREATE TABLE IF NOT EXISTS public.stock_moves (
    id        TEXT PRIMARY KEY,
    date      TEXT,
    stock_id  TEXT,
    model     TEXT,
    direction TEXT,
    qty       NUMERIC DEFAULT 0,
    balance   NUMERIC DEFAULT 0,
    doc_type  TEXT,
    doc_no    TEXT,
    party     TEXT,
    note      TEXT,
    created   TIMESTAMPTZ DEFAULT NOW()
);

-- Seed default admin account (username: admin / password: admin123)
INSERT INTO public.admin (name, email, username, password_hash, role)
VALUES ('System Admin', 'admin@vrstore.com', 'admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'superadmin')
ON CONFLICT (username) DO NOTHING;

-- Seed default AMC pricing settings
INSERT INTO public.settings (key, value) VALUES
  ('amc_pricing', '{"base_1_ton":1999,"base_1_5_ton":2499,"base_2_ton":2999,"cassette_surcharge":500,"comprehensive_multiplier":2}')
ON CONFLICT (key) DO NOTHING;



-- Indexes for high performance
CREATE INDEX IF NOT EXISTS idx_bookings_status     ON public.bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_created_at ON public.bookings(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON public.messages(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_brand      ON public.products(brand);
CREATE INDEX IF NOT EXISTS idx_products_featured   ON public.products(featured);
CREATE INDEX IF NOT EXISTS idx_admin_username      ON public.admin(username);
CREATE INDEX IF NOT EXISTS idx_docs_type_no        ON public.documents(doc_type, doc_no);
CREATE INDEX IF NOT EXISTS idx_stock_model         ON public.stock(model);

-- ── Enable Row Level Security (RLS) ──
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_moves ENABLE ROW LEVEL SECURITY;

-- PUBLIC READ: anyone can view products
DROP POLICY IF EXISTS "Public can read products" ON public.products;
CREATE POLICY "Public can read products" ON public.products FOR SELECT USING (true);

-- ANON INSERT: visitors can submit bookings and messages
DROP POLICY IF EXISTS "Anyone can create bookings" ON public.bookings;
CREATE POLICY "Anyone can create bookings" ON public.bookings FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Anyone can create messages" ON public.messages;
CREATE POLICY "Anyone can create messages" ON public.messages FOR INSERT WITH CHECK (true);

-- FULL ACCESS via publishable/anon key
DROP POLICY IF EXISTS "Anon full access products" ON public.products;
CREATE POLICY "Anon full access products" ON public.products FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Anon full access bookings" ON public.bookings;
CREATE POLICY "Anon full access bookings" ON public.bookings FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Anon full access messages" ON public.messages;
CREATE POLICY "Anon full access messages" ON public.messages FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Anon full access settings" ON public.settings;
CREATE POLICY "Anon full access settings" ON public.settings FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Anon full access admin" ON public.admin;
CREATE POLICY "Anon full access admin" ON public.admin FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Anon full access customers" ON public.customers;
CREATE POLICY "Anon full access customers" ON public.customers FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Anon full access documents" ON public.documents;
CREATE POLICY "Anon full access documents" ON public.documents FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Anon full access stock" ON public.stock;
CREATE POLICY "Anon full access stock" ON public.stock FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Anon full access stock_moves" ON public.stock_moves;
CREATE POLICY "Anon full access stock_moves" ON public.stock_moves FOR ALL USING (true) WITH CHECK (true);
